import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { copyFile } from "node:fs/promises";

const production = process.argv[2] === "production";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

await copyFile("obsidian-plugin/manifest.template.json", "obsidian-plugin/manifest.json");
await copyFile("obsidian-plugin/manifest.template.json", "manifest.json");
await copyFile("obsidian-plugin/styles.source.css", "obsidian-plugin/styles.css");

const context = await esbuild.context({
  banner: {
    js: banner
  },
  bundle: true,
  entryPoints: ["obsidian-plugin/src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((moduleName) => `node:${moduleName}`)
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "obsidian-plugin/main.js",
  platform: "node",
  sourcemap: production ? false : "inline",
  target: "es2022",
  treeShaking: true
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
